# Generated by Django 4.1 on 2022-08-07 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("university", models.CharField(max_length=40)),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("PhD", "PhD"),
                            ("Research", "Research"),
                        ],
                        max_length=15,
                    ),
                ),
                ("field", models.CharField(max_length=30)),
                ("program", models.CharField(max_length=30)),
                ("scholarship_duration", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=25)),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("Full scholarship", "Full scholarship"),
                            ("Partial scholarship", "Partial scholarship"),
                            ("Merit-Based scholarship", "Merit-Based scholarship"),
                            ("Financial scholarship", "Financial scholarship"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"db_table": "scholarships",},
        ),
    ]
