# Generated by Django 4.1 on 2022-08-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("student_phone", models.CharField(max_length=20)),
                ("birthdate", models.DateField()),
                ("country", models.CharField(max_length=50)),
                ("last_grade", models.CharField(max_length=30)),
                ("last_gpa", models.CharField(max_length=5)),
                ("social_network", models.CharField(max_length=50)),
                ("tutor_phone", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
