# Generated by Django 4.1 on 2022-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_org", models.CharField(max_length=50)),
                ("headquarters", models.CharField(max_length=50)),
                ("email_org", models.EmailField(max_length=50)),
                ("phone_org", models.CharField(max_length=20)),
                ("website_org", models.CharField(max_length=50)),
                (
                    "social_media",
                    models.CharField(
                        choices=[
                            ("Facebook", "Facebook"),
                            ("Twitter", "Twitter"),
                            ("Instagram", "Instagram"),
                            ("TikTok", "TikTok"),
                        ],
                        max_length=50,
                    ),
                ),
                ("socialmed_name", models.CharField(max_length=50)),
            ],
            options={"db_table": "organizations",},
        ),
    ]
